version: '2'
services:
  web:
    build: .
    links:
      - mongo
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
  mongo:
     image: mongo
     ports:
       - "27017:27017"
  mongodata:
     image: tianon/true
     volumes:
       - /data/db
